dataset:
  stimuli: pysaliency_datasets/MIT1003/stimuli.hdf5
  fixations: pysaliency_datasets/MIT1003/fixations.hdf5
  filters:
  - type: filter_fixations_by_number
    parameters:
      intervals:
      - [1, 1000]
  - type: remove_out_of_stimulus_fixations

model_type: centerbias
regularizations:
- name: uniform
  type: uniform

maximal_source_count: null

random_search:
  steps: 100