dataset:
  stimuli: pysaliency_datasets/PotsdamCorpus/stimuli.hdf5
  fixations: pysaliency_datasets/PotsdamCorpus/fixations.hdf5
  filters:
  - type: filter_fixations_by_number
    parameters:
      intervals:
      - [1, 1000]
  - type: remove_out_of_stimulus_fixations

log_bandwidth_min: -2.2  # about 0.2 dva

model_type: gold_mixture
regularizations:
- name: uniform
  type: uniform
- name: centerbias
  model_file: centerbias.hdf5

n_jobs: 1
random_search:
  steps: 1000

export_hdf5: False
export_hdf5_mixture: False
export_hdf5_subjects: False