dataset:
  stimuli: pysaliency_datasets/DAEMONS/stimuli_train.hdf5
  fixations: pysaliency_datasets/DAEMONS/fixations_train.hdf5
  filters:
  - type: filter_fixations_by_number
    parameters:
      intervals:
      - [1, 1000]
  - type: remove_out_of_stimulus_fixations

model_type: centerbias
regularizations:
- name: uniform
  type: uniform

maximal_source_count: 100000

# number of jobs to use for parallelization when computing
# crossvalidation performance.
# -1 means use all available cores
n_jobs: -1

random_search:
  steps: 100