defaults:
  - model: schwetlick_MIT
  - priors: strict_MIT_priors
  - init_params: generic_MIT_init

model:
  dynamic_duration: false
  saccadic_momentum: true

init_params:
  saccadic_bias_weigth: 0.5
  momentum_sigma: 1
  return_sigma: 1
  fixation_transition_rate: 0.2
  fixation_transition_midpoint: 3
  long_saccade_threshold: 5.0
  short_saccade_threshold: 2.0

exp_name: training_v1.0.0

pixel_per_degree: 36

MAP_SIZE: 128

val_size: null

optimizer:
  object:
    _convert_: "all"
    _target_: optax.adam
    b1: 0.9
    b2: 0.999
  clip_norm: false
  keep_param_signs: true
  enforce_bounds: false

training:
  epochs: 50
  batch_size: 32
  strategy: "MAP"
  peak_lr: 1.0e-2
  prior_weight: 2
  early_stopping: false
  fix_params: null
  verbose: false

crossvalidation:
  folds: 10
  val_folds: 1
  test_folds: 1

# Hydra-specific
hydra:
  run:
    dir: ./output/hydra/
  searchpath:
    - pkg://deepgaze_vs_scenewalk/configs
