dataset:
  stimuli: pysaliency_datasets/DAEMONS/stimuli_validation.hdf5
  fixations: pysaliency_datasets/DAEMONS/fixations_validation.hdf5
  filters:
  - type: filter_fixations_by_number
    parameters:
      intervals:
      - [1, 1000]
  - type: remove_out_of_stimulus_fixations

log_bandwidth_min: -2.2  # about 0.2 dva

model_type: gold_mixture
regularizations:
- name: uniform
  type: uniform
- name: centerbias
  model_file: centerbias.hdf5
- name: SpatialDeepGaze
  model_file: output/spatial_deepgaze.hdf5

n_jobs: 1
random_search:
  steps: 3000

export_hdf5: False
export_hdf5_mixture: True
export_hdf5_subjects: False