_convert_: all
omegaAttention: 15
omfrac: 10
sigmaAttention: 10.0
sigmaInhib: 9
gamma: 2.0
inhibStrength: 0.1
zeta: -3.0
sigmaShift: 3
shift_size: 0.5
first_fix_OmegaAttention: 3.0
cb_sd_x: 4
cb_sd_y: 3
omega_prevloc_frac: 12
chi: 0.5
ompfactor: -1
t_alpha: 0.8
t_beta: -0.1
t_p: 2.0
