omegaAttention: 473.82023143542676
omegaInhib: 35.073550400347116
sigmaAttention: 7.450827130983052
sigmaInhib: 0.281723548001392
gamma: 0.0
lamb: 0.9644289581070143
inhibStrength: 6.461888024276678e-08
zeta: 0.0040312815350075585
