_convert_: all
omegaAttention: 9.294439739833935
omfrac: 10
sigmaAttention: 15.197573082022966
sigmaInhib: 6.98
gamma: 1.1208945200654843
inhibStrength: 0.3
zeta: -3.020280464296744
sigmaShift: 2
shift_size: 0.39787664871568384
first_fix_OmegaAttention: 1.5
cb_sd_x: 4
cb_sd_y: 3
omega_prevloc_frac: 10
chi: 0.06
ompfactor: -0.6
t_alpha: 0.0027508482663301833
t_beta: -0.9375138457378949
t_p: 2.9650751758640412
