_convert_: all
omegaAttention: 15
omfrac: 10
sigmaAttention: 10.0
sigmaInhib: 9
gamma: 1.2
inhibStrength: 0.1
zeta: -3.0
sigmaShift: 3
shift_size: 0.5
first_fix_OmegaAttention: 3.0
cb_sd_x: 4
cb_sd_y: 3
omega_prevloc_frac: 12
chi: 0.5
ompfactor: -1
t_alpha: 0.8
t_beta: -0.1
t_p: 2.0
## SW-X
saccadic_bias_weigth: 0.5
momentum_sigma: 1
return_sigma: 1
fixation_transition_rate: 0.2
fixation_transition_midpoint: 3
long_saccade_threshold: 5.0
short_saccade_threshold: 2.0
gamma_base: 1.0
gamma_decay: 0.5
alpha_left_bias: 1.2
alpha_vert_bias: 1.1
left_bias_decay_rate: 0.5
dir_bias_growth_rate: 0.5
