defaults:
  - model: SW_X_MIT
  - priors: strict_MIT_priors
  - init_params: SW_X_MIT_init

model:
  dynamic_duration: false

exp_name: training_v1.0.0

pixel_per_degree: 36

MAP_SIZE: 128

val_size: null

optimizer:
  object:
    _convert_: "all"
    _target_: optax.adam
    b1: 0.9
    b2: 0.999
  clip_norm: false
  keep_param_signs: true
  enforce_bounds: false

training:
  epochs: 50
  batch_size: 32
  strategy: "MAP"
  peak_lr: 1.0e-2
  prior_weight: 2
  early_stopping: false
  fix_params: null
  verbose: false

crossvalidation:
  folds: 10
  val_folds: 1
  test_folds: 1

# Hydra-specific
hydra:
  run:
    dir: ./output/hydra/
  searchpath:
    - pkg://deepgaze_vs_scenewalk/configs
