_convert_: all
inhib_method: "subtractive"
att_map_init_type: "cb"
shifts: "both"
locdep_decay_switch: "on"
omp: "add"
dynamic_duration: true
data_range:
  x: [0.0, 28.50608869]
  y: [0.0, 21.37956652]
kwargs_dict:
  coupled_oms: true
  saclen_shift: true
  coupled_facil: true
  exponents: 1
  logged_z: true
  logged_ompf: true
inputs_in_deg: true
