defaults:
  - model: schwetlick_MIT
  - priors: strict_MIT_priors
  - init_params: generic_MIT_init

model:
  dynamic_duration: false
  early_fix_exponents_scaling: true
  saccadic_momentum: true
  kwargs_dict:
    exponents: 1
  data_range:
    x: [0.0, 34.5]
    y: [0.0, 27.5]
    # The original SW uses these values:
    # x: [1.03585769, 32.1115885]
    # y: [0.82868615, 25.6892708]

init_params:
  gamma_base: 1.0
  gamma_decay: 0.5
  gamma: 1.2
  saccadic_bias_weigth: 0.5
  momentum_sigma: 1
  return_sigma: 1
  fixation_transition_rate: 0.2
  fixation_transition_midpoint: 3
  long_saccade_threshold: 5.0
  short_saccade_threshold: 2.0

exp_name: training_v1.0.0

pixel_per_degree: 38.58

MAP_SIZE: 128

val_size: null

optimizer:
  object:
    _convert_: "all"
    _target_: optax.adam
    b1: 0.9
    b2: 0.999
  clip_norm: false
  keep_param_signs: true
  enforce_bounds: false

training:
  epochs: 50
  batch_size: 32
  strategy: "MAP"
  peak_lr: 1.0e-2
  prior_weight: 2
  early_stopping: false
  fix_params: null
  verbose: false

crossvalidation:
  folds: 10
  val_folds: 1
  test_folds: 1

# Hydra-specific
hydra:
  run:
    dir: ./output/hydra/
  searchpath:
    - pkg://deepgaze_vs_scenewalk/configs
