defaults:
  - model: schwetlick_MIT
  - priors: strict_MIT_priors
  - init_params: generic_MIT_init

model:
  dynamic_duration: false
  data_range:
    x: [0.0, 55] # Original paper reports 54
    y: [0.0, 35]
  omp: "attention"

init_params:
  alpha_left_bias: 1.2
  alpha_vert_bias: 1.1
  ompfactor: -1.0
  left_bias_decay_rate: 0.5
  dir_bias_growth_rate: 0.5

exp_name: "COCO-Freeview_training_v1.0.0"

pixel_per_degree: 30.6

MAP_SIZE: 128

val_size: null

optimizer:
  object:
    _convert_: "all"
    _target_: optax.adam
    b1: 0.9
    b2: 0.999
  clip_norm: false
  keep_param_signs: true
  enforce_bounds: false

training:
  epochs: 50
  batch_size: 32
  strategy: "MAP"
  peak_lr: 1.0e-2
  prior_weight: 2
  early_stopping: false
  fix_params: null
  verbose: false

# Hydra-specific
hydra:
  run:
    dir: ./output/hydra/
  searchpath:
    - pkg://deepgaze_vs_scenewalk/configs
